version: '3.4'
services:
  devexchange.server:
    image: ${DOCKER_REGISTRY-}devexchangeserver
    ports:
      - "5000:80"
      - "5001:443"
    build:
      context: .
      dockerfile: Devexchange.Server/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - RUNNING_IN_DOCKER=true
    depends_on:
      - sql-server
  
  devexchange.client:
    build:
      context: ./devexchange.client
      dockerfile: Dockerfile
    ports:
      - "3000:5713"
    environment:
      - NODE_ENV=development
      - RUNNING_IN_DOCKER=true
      - VITE_API_URL=https://localhost:5001
    
    depends_on:
      - devexchange.server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

volumes:
  sql-data: